fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    archive: git://github.com/camptocamp/puppet-archive.git
    vcsrepo: git://github.com/puppetlabs/puppetlabs-vcsrepo.git
  symlinks:
    diamond: "#{source_dir}"
